default: &default
  adapter: sqlite3
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: toy_app_test

production:
 url: <%= ENV['DATABASE_URL'] %>
 
   <<: *default
   adapter: postgresql
#   database: db/production.sqlite3
 database: toy_app_production
  #username: toy_app
  #password: <%= ENV['TOY_APP_DATABASE_PASSWORD'] %>

